// Code generated by pigeon; DO NOT EDIT.

package main

import (
	"bytes"
	"errors"
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"

	"github.com/fy0/pigeon/ast"
)

type ParserCustomData struct{}

var g = &grammar{
	rules: []*rule{
		{
			name:      "Grammar",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onGrammar_1,
				expr: &seqExpr{
					exprs: []any{
						&ruleRefExpr{name: "__"},
						&labeledExpr{
							label: "initializer",
							expr: &zeroOrOneExpr{
								expr: &actionExpr{
									run: (*parser).call_onGrammar_6,
									expr: &seqExpr{
										exprs: []any{
											&labeledExpr{
												label: "i",
												expr:  &ruleRefExpr{name: "Initializer"},
											},
											&ruleRefExpr{name: "__"},
										},
									},
								},
							},
						},
						&labeledExpr{
							label: "rules",
							expr: &oneOrMoreExpr{
								expr: &actionExpr{
									run: (*parser).call_onGrammar_13,
									expr: &seqExpr{
										exprs: []any{
											&labeledExpr{
												label: "r",
												expr:  &ruleRefExpr{name: "Rule"},
											},
											&ruleRefExpr{name: "__"},
										},
									},
								},
							},
						},
						&ruleRefExpr{name: "EOF"},
					},
				},
			},
		},
		{
			name:      "Initializer",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onInitializer_1,
				expr: &seqExpr{
					exprs: []any{
						&labeledExpr{
							label: "code",
							expr:  &ruleRefExpr{name: "CodeBlock"},
						},
						&ruleRefExpr{name: "EOS"},
					},
				},
			},
		},
		{
			name:      "Rule",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onRule_1,
				expr: &seqExpr{
					exprs: []any{
						&labeledExpr{
							label: "name",
							expr:  &ruleRefExpr{name: "IdentifierName"},
						},
						&ruleRefExpr{name: "__"},
						&labeledExpr{
							label: "display",
							expr: &zeroOrOneExpr{
								expr: &actionExpr{
									run: (*parser).call_onRule_8,
									expr: &seqExpr{
										exprs: []any{
											&labeledExpr{
												label: "sl",
												expr:  &ruleRefExpr{name: "StringLiteral"},
											},
											&ruleRefExpr{name: "__"},
										},
									},
								},
							},
						},
						&ruleRefExpr{name: "RuleDefOp"},
						&ruleRefExpr{name: "__"},
						&labeledExpr{
							label: "expr",
							expr:  &ruleRefExpr{name: "Expression"},
						},
						&ruleRefExpr{name: "EOS"},
					},
				},
			},
		},
		{
			name: "Expression",
			expr: &ruleRefExpr{name: "RecoveryExpr"},
		},
		{
			name:      "RecoveryExpr",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onRecoveryExpr_1,
				expr: &seqExpr{
					exprs: []any{
						&labeledExpr{
							label: "expr",
							expr:  &ruleRefExpr{name: "ChoiceExpr"},
						},
						&labeledExpr{
							label: "recoverExprs",
							expr: &zeroOrMoreExpr{
								expr: &actionExpr{
									run: (*parser).call_onRecoveryExpr_7,
									expr: &seqExpr{
										exprs: []any{
											&ruleRefExpr{name: "__"},
											&litMatcher{val: "//{", want: "\"//{\""},
											&ruleRefExpr{name: "__"},
											&labeledExpr{
												label: "lbs",
												expr:  &ruleRefExpr{name: "Labels"},
											},
											&ruleRefExpr{name: "__"},
											&litMatcher{val: "}", want: "\"}\""},
											&ruleRefExpr{name: "__"},
											&labeledExpr{
												label: "ce",
												expr:  &ruleRefExpr{name: "ChoiceExpr"},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name:      "Labels",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onLabels_1,
				expr: &seqExpr{
					exprs: []any{
						&labeledExpr{
							label: "label",
							expr:  &ruleRefExpr{name: "IdentifierName"},
						},
						&labeledExpr{
							label: "labels",
							expr: &zeroOrMoreExpr{
								expr: &actionExpr{
									run: (*parser).call_onLabels_7,
									expr: &seqExpr{
										exprs: []any{
											&ruleRefExpr{name: "__"},
											&litMatcher{val: ",", want: "\",\""},
											&ruleRefExpr{name: "__"},
											&labeledExpr{
												label: "id",
												expr:  &ruleRefExpr{name: "IdentifierName"},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name:      "ChoiceExpr",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onChoiceExpr_1,
				expr: &seqExpr{
					exprs: []any{
						&labeledExpr{
							label: "first",
							expr:  &ruleRefExpr{name: "ActionSeqExpr"},
						},
						&labeledExpr{
							label: "rest",
							expr: &zeroOrMoreExpr{
								expr: &actionExpr{
									run: (*parser).call_onChoiceExpr_7,
									expr: &seqExpr{
										exprs: []any{
											&ruleRefExpr{name: "__"},
											&litMatcher{val: "/", want: "\"/\""},
											&ruleRefExpr{name: "__"},
											&labeledExpr{
												label: "ase",
												expr:  &ruleRefExpr{name: "ActionSeqExpr"},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name:      "ActionSeqExpr",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onActionSeqExpr_1,
				expr: &seqExpr{
					exprs: []any{
						&labeledExpr{
							label: "first",
							expr:  &ruleRefExpr{name: "ActionExpr"},
						},
						&labeledExpr{
							label: "rest",
							expr: &zeroOrMoreExpr{
								expr: &actionExpr{
									run: (*parser).call_onActionSeqExpr_7,
									expr: &seqExpr{
										exprs: []any{
											&ruleRefExpr{name: "__"},
											&labeledExpr{
												label: "ae",
												expr:  &ruleRefExpr{name: "ActionExpr"},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name:      "ActionExpr",
			varExists: true,
			expr: &choiceExpr{
				alternatives: []any{
					&actionExpr{
						run: (*parser).call_onActionExpr_2,
						expr: &seqExpr{
							exprs: []any{
								&labeledExpr{
									label: "expr",
									expr:  &ruleRefExpr{name: "SeqExpr"},
								},
								&labeledExpr{
									label: "code",
									expr: &zeroOrOneExpr{
										expr: &actionExpr{
											run: (*parser).call_onActionExpr_8,
											expr: &seqExpr{
												exprs: []any{
													&ruleRefExpr{name: "__"},
													&labeledExpr{
														label: "cb",
														expr:  &ruleRefExpr{name: "CodeBlock"},
													},
												},
											},
										},
									},
								},
							},
						},
					},
					&actionExpr{
						run: (*parser).call_onActionExpr_13,
						expr: &seqExpr{
							exprs: []any{
								&ruleRefExpr{name: "__"},
								&labeledExpr{
									label: "code",
									expr:  &ruleRefExpr{name: "CodeBlock"},
								},
							},
						},
					},
				},
			},
		},
		{
			name:      "SeqExpr",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onSeqExpr_1,
				expr: &seqExpr{
					exprs: []any{
						&labeledExpr{
							label: "first",
							expr:  &ruleRefExpr{name: "LabeledExpr"},
						},
						&labeledExpr{
							label: "rest",
							expr: &zeroOrMoreExpr{
								expr: &actionExpr{
									run: (*parser).call_onSeqExpr_7,
									expr: &seqExpr{
										exprs: []any{
											&ruleRefExpr{name: "__"},
											&labeledExpr{
												label: "le",
												expr:  &ruleRefExpr{name: "LabeledExpr"},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name:      "LabeledExpr",
			varExists: true,
			expr: &choiceExpr{
				alternatives: []any{
					&actionExpr{
						run: (*parser).call_onLabeledExpr_2,
						expr: &seqExpr{
							exprs: []any{
								&labeledExpr{
									label: "label",
									expr:  &ruleRefExpr{name: "Identifier"},
								},
								&ruleRefExpr{name: "__"},
								&litMatcher{val: ":", want: "\":\""},
								&ruleRefExpr{name: "__"},
								&litMatcher{val: "<", want: "\"<\""},
								&ruleRefExpr{name: "__"},
								&labeledExpr{
									label: "expr",
									expr:  &ruleRefExpr{name: "PrefixedExpr"},
								},
								&ruleRefExpr{name: "__"},
								&litMatcher{val: ">", want: "\">\""},
							},
						},
					},
					&actionExpr{
						run: (*parser).call_onLabeledExpr_15,
						expr: &seqExpr{
							exprs: []any{
								&labeledExpr{
									label: "label",
									expr:  &ruleRefExpr{name: "Identifier"},
								},
								&ruleRefExpr{name: "__"},
								&litMatcher{val: ":", want: "\":\""},
								&ruleRefExpr{name: "__"},
								&labeledExpr{
									label: "expr",
									expr:  &ruleRefExpr{name: "PrefixedExpr"},
								},
							},
						},
					},
					&ruleRefExpr{name: "PrefixedExpr"},
					&ruleRefExpr{name: "ThrowExpr"},
				},
			},
		},
		{
			name:      "PrefixedExpr",
			varExists: true,
			expr: &choiceExpr{
				alternatives: []any{
					&actionExpr{
						run: (*parser).call_onPrefixedExpr_2,
						expr: &seqExpr{
							exprs: []any{
								&labeledExpr{
									label: "op",
									expr:  &ruleRefExpr{name: "PrefixedOp"},
								},
								&ruleRefExpr{name: "__"},
								&labeledExpr{
									label: "expr",
									expr:  &ruleRefExpr{name: "SuffixedExpr"},
								},
							},
						},
					},
					&ruleRefExpr{name: "SuffixedExpr"},
				},
			},
		},
		{
			name: "PrefixedOp",
			expr: &actionExpr{
				run: (*parser).call_onPrefixedOp_1,
				expr: &choiceExpr{
					alternatives: []any{
						&litMatcher{val: "&&", want: "\"&&\""},
						&litMatcher{val: "!!", want: "\"!!\""},
						&litMatcher{val: "&", want: "\"&\""},
						&litMatcher{val: "!", want: "\"!\""},
					},
				},
			},
		},
		{
			name:      "SuffixedExpr",
			varExists: true,
			expr: &choiceExpr{
				alternatives: []any{
					&actionExpr{
						run: (*parser).call_onSuffixedExpr_2,
						expr: &seqExpr{
							exprs: []any{
								&labeledExpr{
									label: "expr",
									expr:  &ruleRefExpr{name: "PrimaryExpr"},
								},
								&labeledExpr{
									label: "op",
									expr:  &ruleRefExpr{name: "SuffixedOp"},
								},
							},
						},
					},
					&ruleRefExpr{name: "PrimaryExpr"},
				},
			},
		},
		{
			name: "SuffixedOp",
			expr: &actionExpr{
				run: (*parser).call_onSuffixedOp_1,
				expr: &choiceExpr{
					alternatives: []any{
						&litMatcher{val: "?", want: "\"?\""},
						&litMatcher{val: "*", want: "\"*\""},
						&litMatcher{val: "+", want: "\"+\""},
					},
				},
			},
		},
		{
			name:      "PrimaryExpr",
			varExists: true,
			expr: &choiceExpr{
				alternatives: []any{
					&ruleRefExpr{name: "LitMatcher"},
					&ruleRefExpr{name: "CharClassMatcher"},
					&ruleRefExpr{name: "AnyMatcher"},
					&ruleRefExpr{name: "RuleRefExpr"},
					&ruleRefExpr{name: "SemanticPredExpr"},
					&actionExpr{
						run: (*parser).call_onPrimaryExpr_7,
						expr: &seqExpr{
							exprs: []any{
								&litMatcher{val: "(", want: "\"(\""},
								&ruleRefExpr{name: "__"},
								&labeledExpr{
									label: "expr",
									expr:  &ruleRefExpr{name: "Expression"},
								},
								&ruleRefExpr{name: "__"},
								&litMatcher{val: ")", want: "\")\""},
							},
						},
					},
				},
			},
		},
		{
			name:      "RuleRefExpr",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onRuleRefExpr_1,
				expr: &seqExpr{
					exprs: []any{
						&labeledExpr{
							label: "name",
							expr:  &ruleRefExpr{name: "IdentifierName"},
						},
						&notExpr{
							expr: &seqExpr{
								exprs: []any{
									&ruleRefExpr{name: "__"},
									&zeroOrOneExpr{
										expr: &seqExpr{
											exprs: []any{
												&ruleRefExpr{name: "StringLiteral"},
												&ruleRefExpr{name: "__"},
											},
										},
									},
									&ruleRefExpr{name: "RuleDefOp"},
								},
							},
						},
					},
				},
			},
		},
		{
			name:      "SemanticPredExpr",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onSemanticPredExpr_1,
				expr: &seqExpr{
					exprs: []any{
						&labeledExpr{
							label: "op",
							expr:  &ruleRefExpr{name: "SemanticPredOp"},
						},
						&ruleRefExpr{name: "__"},
						&labeledExpr{
							label: "code",
							expr:  &ruleRefExpr{name: "CodeBlock"},
						},
					},
				},
			},
		},
		{
			name: "SemanticPredOp",
			expr: &actionExpr{
				run: (*parser).call_onSemanticPredOp_1,
				expr: &choiceExpr{
					alternatives: []any{
						&litMatcher{val: "&", want: "\"&\""},
						&litMatcher{val: "!", want: "\"!\""},
						&litMatcher{val: "*", want: "\"*\""},
					},
				},
			},
		},
		{
			name: "RuleDefOp",
			expr: &choiceExpr{
				alternatives: []any{
					&litMatcher{val: "=", want: "\"=\""},
					&litMatcher{val: "<-", want: "\"<-\""},
					&litMatcher{val: "←", want: "\"←\""},
					&litMatcher{val: "⟵", want: "\"⟵\""},
				},
			},
		},
		{
			name: "SourceChar",
			expr: &anyMatcher{},
		},
		{
			name: "Comment",
			expr: &choiceExpr{
				alternatives: []any{
					&ruleRefExpr{name: "MultiLineComment"},
					&ruleRefExpr{name: "SingleLineComment"},
				},
			},
		},
		{
			name: "MultiLineComment",
			expr: &seqExpr{
				exprs: []any{
					&litMatcher{val: "/*", want: "\"/*\""},
					&zeroOrMoreExpr{
						expr: &seqExpr{
							exprs: []any{
								&notExpr{
									expr: &litMatcher{val: "*/", want: "\"*/\""},
								},
								&ruleRefExpr{name: "SourceChar"},
							},
						},
					},
					&litMatcher{val: "*/", want: "\"*/\""},
				},
			},
		},
		{
			name: "MultiLineCommentNoLineTerminator",
			expr: &seqExpr{
				exprs: []any{
					&litMatcher{val: "/*", want: "\"/*\""},
					&zeroOrMoreExpr{
						expr: &seqExpr{
							exprs: []any{
								&notExpr{
									expr: &choiceExpr{
										alternatives: []any{
											&litMatcher{val: "*/", want: "\"*/\""},
											&ruleRefExpr{name: "EOL"},
										},
									},
								},
								&ruleRefExpr{name: "SourceChar"},
							},
						},
					},
					&litMatcher{val: "*/", want: "\"*/\""},
				},
			},
		},
		{
			name: "SingleLineComment",
			expr: &seqExpr{
				exprs: []any{
					&notExpr{
						expr: &litMatcher{val: "//{", want: "\"//{\""},
					},
					&litMatcher{val: "//", want: "\"//\""},
					&zeroOrMoreExpr{
						expr: &seqExpr{
							exprs: []any{
								&notExpr{
									expr: &ruleRefExpr{name: "EOL"},
								},
								&ruleRefExpr{name: "SourceChar"},
							},
						},
					},
				},
			},
		},
		{
			name:      "Identifier",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onIdentifier_1,
				expr: &labeledExpr{
					label: "ident",
					expr:  &ruleRefExpr{name: "IdentifierName"},
				},
			},
		},
		{
			name: "IdentifierName",
			expr: &actionExpr{
				run: (*parser).call_onIdentifierName_1,
				expr: &seqExpr{
					exprs: []any{
						&ruleRefExpr{name: "IdentifierStart"},
						&zeroOrMoreExpr{
							expr: &ruleRefExpr{name: "IdentifierPart"},
						},
					},
				},
			},
		},
		{
			name: "IdentifierStart",
			expr: &charClassMatcher{
				val:     "[\\pL_]",
				chars:   []rune{'_'},
				classes: []*unicode.RangeTable{unicode.L},
			},
		},
		{
			name: "IdentifierPart",
			expr: &choiceExpr{
				alternatives: []any{
					&ruleRefExpr{name: "IdentifierStart"},
					&charClassMatcher{
						val:     "[\\p{Nd}]",
						classes: []*unicode.RangeTable{unicode.Nd},
					},
				},
			},
		},
		{
			name:      "LitMatcher",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onLitMatcher_1,
				expr: &seqExpr{
					exprs: []any{
						&labeledExpr{
							label: "lit",
							expr:  &ruleRefExpr{name: "StringLiteral"},
						},
						&labeledExpr{
							label: "ignore",
							expr: &zeroOrOneExpr{
								expr: &litMatcher{val: "i", want: "\"i\""},
							},
						},
					},
				},
			},
		},
		{
			name: "StringLiteral",
			expr: &choiceExpr{
				alternatives: []any{
					&actionExpr{
						run: (*parser).call_onStringLiteral_2,
						expr: &choiceExpr{
							alternatives: []any{
								&seqExpr{
									exprs: []any{
										&litMatcher{val: "\"", want: "\"\\\"\""},
										&zeroOrMoreExpr{
											expr: &ruleRefExpr{name: "DoubleStringChar"},
										},
										&litMatcher{val: "\"", want: "\"\\\"\""},
									},
								},
								&seqExpr{
									exprs: []any{
										&litMatcher{val: "'", want: "\"'\""},
										&ruleRefExpr{name: "SingleStringChar"},
										&litMatcher{val: "'", want: "\"'\""},
									},
								},
								&seqExpr{
									exprs: []any{
										&litMatcher{val: "`", want: "\"`\""},
										&zeroOrMoreExpr{
											expr: &ruleRefExpr{name: "RawStringChar"},
										},
										&litMatcher{val: "`", want: "\"`\""},
									},
								},
							},
						},
					},
					&actionExpr{
						run: (*parser).call_onStringLiteral_18,
						expr: &choiceExpr{
							alternatives: []any{
								&seqExpr{
									exprs: []any{
										&litMatcher{val: "\"", want: "\"\\\"\""},
										&zeroOrMoreExpr{
											expr: &ruleRefExpr{name: "DoubleStringChar"},
										},
										&choiceExpr{
											alternatives: []any{
												&ruleRefExpr{name: "EOL"},
												&ruleRefExpr{name: "EOF"},
											},
										},
									},
								},
								&seqExpr{
									exprs: []any{
										&litMatcher{val: "'", want: "\"'\""},
										&zeroOrOneExpr{
											expr: &ruleRefExpr{name: "SingleStringChar"},
										},
										&choiceExpr{
											alternatives: []any{
												&ruleRefExpr{name: "EOL"},
												&ruleRefExpr{name: "EOF"},
											},
										},
									},
								},
								&seqExpr{
									exprs: []any{
										&litMatcher{val: "`", want: "\"`\""},
										&zeroOrMoreExpr{
											expr: &ruleRefExpr{name: "RawStringChar"},
										},
										&ruleRefExpr{name: "EOF"},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "DoubleStringChar",
			expr: &choiceExpr{
				alternatives: []any{
					&seqExpr{
						exprs: []any{
							&notExpr{
								expr: &choiceExpr{
									alternatives: []any{
										&litMatcher{val: "\"", want: "\"\\\"\""},
										&litMatcher{val: "\\", want: "\"\\\\\""},
										&ruleRefExpr{name: "EOL"},
									},
								},
							},
							&ruleRefExpr{name: "SourceChar"},
						},
					},
					&seqExpr{
						exprs: []any{
							&litMatcher{val: "\\", want: "\"\\\\\""},
							&ruleRefExpr{name: "DoubleStringEscape"},
						},
					},
				},
			},
		},
		{
			name: "SingleStringChar",
			expr: &choiceExpr{
				alternatives: []any{
					&seqExpr{
						exprs: []any{
							&notExpr{
								expr: &choiceExpr{
									alternatives: []any{
										&litMatcher{val: "'", want: "\"'\""},
										&litMatcher{val: "\\", want: "\"\\\\\""},
										&ruleRefExpr{name: "EOL"},
									},
								},
							},
							&ruleRefExpr{name: "SourceChar"},
						},
					},
					&seqExpr{
						exprs: []any{
							&litMatcher{val: "\\", want: "\"\\\\\""},
							&ruleRefExpr{name: "SingleStringEscape"},
						},
					},
				},
			},
		},
		{
			name: "RawStringChar",
			expr: &seqExpr{
				exprs: []any{
					&notExpr{
						expr: &litMatcher{val: "`", want: "\"`\""},
					},
					&ruleRefExpr{name: "SourceChar"},
				},
			},
		},
		{
			name: "DoubleStringEscape",
			expr: &choiceExpr{
				alternatives: []any{
					&choiceExpr{
						alternatives: []any{
							&litMatcher{val: "\"", want: "\"\\\"\""},
							&ruleRefExpr{name: "CommonEscapeSequence"},
						},
					},
					&actionExpr{
						run: (*parser).call_onDoubleStringEscape_5,
						expr: &choiceExpr{
							alternatives: []any{
								&ruleRefExpr{name: "SourceChar"},
								&ruleRefExpr{name: "EOL"},
								&ruleRefExpr{name: "EOF"},
							},
						},
					},
				},
			},
		},
		{
			name: "SingleStringEscape",
			expr: &choiceExpr{
				alternatives: []any{
					&choiceExpr{
						alternatives: []any{
							&litMatcher{val: "'", want: "\"'\""},
							&ruleRefExpr{name: "CommonEscapeSequence"},
						},
					},
					&actionExpr{
						run: (*parser).call_onSingleStringEscape_5,
						expr: &choiceExpr{
							alternatives: []any{
								&ruleRefExpr{name: "SourceChar"},
								&ruleRefExpr{name: "EOL"},
								&ruleRefExpr{name: "EOF"},
							},
						},
					},
				},
			},
		},
		{
			name: "CommonEscapeSequence",
			expr: &choiceExpr{
				alternatives: []any{
					&ruleRefExpr{name: "SingleCharEscape"},
					&ruleRefExpr{name: "OctalEscape"},
					&ruleRefExpr{name: "HexEscape"},
					&ruleRefExpr{name: "LongUnicodeEscape"},
					&ruleRefExpr{name: "ShortUnicodeEscape"},
				},
			},
		},
		{
			name: "SingleCharEscape",
			expr: &choiceExpr{
				alternatives: []any{
					&litMatcher{val: "a", want: "\"a\""},
					&litMatcher{val: "b", want: "\"b\""},
					&litMatcher{val: "n", want: "\"n\""},
					&litMatcher{val: "f", want: "\"f\""},
					&litMatcher{val: "r", want: "\"r\""},
					&litMatcher{val: "t", want: "\"t\""},
					&litMatcher{val: "v", want: "\"v\""},
					&litMatcher{val: "\\", want: "\"\\\\\""},
				},
			},
		},
		{
			name: "OctalEscape",
			expr: &choiceExpr{
				alternatives: []any{
					&seqExpr{
						exprs: []any{
							&ruleRefExpr{name: "OctalDigit"},
							&ruleRefExpr{name: "OctalDigit"},
							&ruleRefExpr{name: "OctalDigit"},
						},
					},
					&actionExpr{
						run: (*parser).call_onOctalEscape_6,
						expr: &seqExpr{
							exprs: []any{
								&ruleRefExpr{name: "OctalDigit"},
								&choiceExpr{
									alternatives: []any{
										&ruleRefExpr{name: "SourceChar"},
										&ruleRefExpr{name: "EOL"},
										&ruleRefExpr{name: "EOF"},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "HexEscape",
			expr: &choiceExpr{
				alternatives: []any{
					&seqExpr{
						exprs: []any{
							&litMatcher{val: "x", want: "\"x\""},
							&ruleRefExpr{name: "HexDigit"},
							&ruleRefExpr{name: "HexDigit"},
						},
					},
					&actionExpr{
						run: (*parser).call_onHexEscape_6,
						expr: &seqExpr{
							exprs: []any{
								&litMatcher{val: "x", want: "\"x\""},
								&choiceExpr{
									alternatives: []any{
										&ruleRefExpr{name: "SourceChar"},
										&ruleRefExpr{name: "EOL"},
										&ruleRefExpr{name: "EOF"},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "LongUnicodeEscape",
			expr: &choiceExpr{
				alternatives: []any{
					&actionExpr{
						run: (*parser).call_onLongUnicodeEscape_2,
						expr: &seqExpr{
							exprs: []any{
								&litMatcher{val: "U", want: "\"U\""},
								&ruleRefExpr{name: "HexDigit"},
								&ruleRefExpr{name: "HexDigit"},
								&ruleRefExpr{name: "HexDigit"},
								&ruleRefExpr{name: "HexDigit"},
								&ruleRefExpr{name: "HexDigit"},
								&ruleRefExpr{name: "HexDigit"},
								&ruleRefExpr{name: "HexDigit"},
								&ruleRefExpr{name: "HexDigit"},
							},
						},
					},
					&actionExpr{
						run: (*parser).call_onLongUnicodeEscape_13,
						expr: &seqExpr{
							exprs: []any{
								&litMatcher{val: "U", want: "\"U\""},
								&choiceExpr{
									alternatives: []any{
										&ruleRefExpr{name: "SourceChar"},
										&ruleRefExpr{name: "EOL"},
										&ruleRefExpr{name: "EOF"},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ShortUnicodeEscape",
			expr: &choiceExpr{
				alternatives: []any{
					&actionExpr{
						run: (*parser).call_onShortUnicodeEscape_2,
						expr: &seqExpr{
							exprs: []any{
								&litMatcher{val: "u", want: "\"u\""},
								&ruleRefExpr{name: "HexDigit"},
								&ruleRefExpr{name: "HexDigit"},
								&ruleRefExpr{name: "HexDigit"},
								&ruleRefExpr{name: "HexDigit"},
							},
						},
					},
					&actionExpr{
						run: (*parser).call_onShortUnicodeEscape_9,
						expr: &seqExpr{
							exprs: []any{
								&litMatcher{val: "u", want: "\"u\""},
								&choiceExpr{
									alternatives: []any{
										&ruleRefExpr{name: "SourceChar"},
										&ruleRefExpr{name: "EOL"},
										&ruleRefExpr{name: "EOF"},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "OctalDigit",
			expr: &charClassMatcher{
				val:    "[0-7]",
				ranges: []rune{'0', '7'},
			},
		},
		{
			name: "DecimalDigit",
			expr: &charClassMatcher{
				val:    "[0-9]",
				ranges: []rune{'0', '9'},
			},
		},
		{
			name: "HexDigit",
			expr: &charClassMatcher{
				val:        "[0-9a-f]i",
				ranges:     []rune{'0', '9', 'a', 'f'},
				ignoreCase: true,
			},
		},
		{
			name: "CharClassMatcher",
			expr: &choiceExpr{
				alternatives: []any{
					&actionExpr{
						run: (*parser).call_onCharClassMatcher_2,
						expr: &seqExpr{
							exprs: []any{
								&litMatcher{val: "[", want: "\"[\""},
								&zeroOrMoreExpr{
									expr: &choiceExpr{
										alternatives: []any{
											&ruleRefExpr{name: "ClassCharRange"},
											&ruleRefExpr{name: "ClassChar"},
											&seqExpr{
												exprs: []any{
													&litMatcher{val: "\\", want: "\"\\\\\""},
													&ruleRefExpr{name: "UnicodeClassEscape"},
												},
											},
										},
									},
								},
								&litMatcher{val: "]", want: "\"]\""},
								&zeroOrOneExpr{
									expr: &litMatcher{val: "i", want: "\"i\""},
								},
							},
						},
					},
					&actionExpr{
						run: (*parser).call_onCharClassMatcher_15,
						expr: &seqExpr{
							exprs: []any{
								&litMatcher{val: "[", want: "\"[\""},
								&zeroOrMoreExpr{
									expr: &seqExpr{
										exprs: []any{
											&notExpr{
												expr: &ruleRefExpr{name: "EOL"},
											},
											&ruleRefExpr{name: "SourceChar"},
										},
									},
								},
								&choiceExpr{
									alternatives: []any{
										&ruleRefExpr{name: "EOL"},
										&ruleRefExpr{name: "EOF"},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "ClassCharRange",
			expr: &seqExpr{
				exprs: []any{
					&ruleRefExpr{name: "ClassChar"},
					&litMatcher{val: "-", want: "\"-\""},
					&ruleRefExpr{name: "ClassChar"},
				},
			},
		},
		{
			name: "ClassChar",
			expr: &choiceExpr{
				alternatives: []any{
					&seqExpr{
						exprs: []any{
							&notExpr{
								expr: &choiceExpr{
									alternatives: []any{
										&litMatcher{val: "]", want: "\"]\""},
										&litMatcher{val: "\\", want: "\"\\\\\""},
										&ruleRefExpr{name: "EOL"},
									},
								},
							},
							&ruleRefExpr{name: "SourceChar"},
						},
					},
					&seqExpr{
						exprs: []any{
							&litMatcher{val: "\\", want: "\"\\\\\""},
							&ruleRefExpr{name: "CharClassEscape"},
						},
					},
				},
			},
		},
		{
			name: "CharClassEscape",
			expr: &choiceExpr{
				alternatives: []any{
					&choiceExpr{
						alternatives: []any{
							&litMatcher{val: "]", want: "\"]\""},
							&ruleRefExpr{name: "CommonEscapeSequence"},
						},
					},
					&actionExpr{
						run: (*parser).call_onCharClassEscape_5,
						expr: &seqExpr{
							exprs: []any{
								&notExpr{
									expr: &litMatcher{val: "p", want: "\"p\""},
								},
								&choiceExpr{
									alternatives: []any{
										&ruleRefExpr{name: "SourceChar"},
										&ruleRefExpr{name: "EOL"},
										&ruleRefExpr{name: "EOF"},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name:      "UnicodeClassEscape",
			varExists: true,
			expr: &seqExpr{
				exprs: []any{
					&litMatcher{val: "p", want: "\"p\""},
					&choiceExpr{
						alternatives: []any{
							&ruleRefExpr{name: "SingleCharUnicodeClass"},
							&actionExpr{
								run: (*parser).call_onUnicodeClassEscape_5,
								expr: &seqExpr{
									exprs: []any{
										&notExpr{
											expr: &litMatcher{val: "{", want: "\"{\""},
										},
										&choiceExpr{
											alternatives: []any{
												&ruleRefExpr{name: "SourceChar"},
												&ruleRefExpr{name: "EOL"},
												&ruleRefExpr{name: "EOF"},
											},
										},
									},
								},
							},
							&actionExpr{
								run: (*parser).call_onUnicodeClassEscape_13,
								expr: &seqExpr{
									exprs: []any{
										&litMatcher{val: "{", want: "\"{\""},
										&labeledExpr{
											label: "ident",
											expr:  &ruleRefExpr{name: "IdentifierName"},
										},
										&litMatcher{val: "}", want: "\"}\""},
									},
								},
							},
							&actionExpr{
								run: (*parser).call_onUnicodeClassEscape_19,
								expr: &seqExpr{
									exprs: []any{
										&litMatcher{val: "{", want: "\"{\""},
										&ruleRefExpr{name: "IdentifierName"},
										&choiceExpr{
											alternatives: []any{
												&litMatcher{val: "]", want: "\"]\""},
												&ruleRefExpr{name: "EOL"},
												&ruleRefExpr{name: "EOF"},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "SingleCharUnicodeClass",
			expr: &charClassMatcher{
				val:   "[LMNCPZS]",
				chars: []rune{'L', 'M', 'N', 'C', 'P', 'Z', 'S'},
			},
		},
		{
			name: "AnyMatcher",
			expr: &actionExpr{
				run:  (*parser).call_onAnyMatcher_1,
				expr: &litMatcher{val: ".", want: "\".\""},
			},
		},
		{
			name:      "ThrowExpr",
			varExists: true,
			expr: &choiceExpr{
				alternatives: []any{
					&actionExpr{
						run: (*parser).call_onThrowExpr_2,
						expr: &seqExpr{
							exprs: []any{
								&litMatcher{val: "%", want: "\"%\""},
								&litMatcher{val: "{", want: "\"{\""},
								&labeledExpr{
									label: "label",
									expr:  &ruleRefExpr{name: "IdentifierName"},
								},
								&litMatcher{val: "}", want: "\"}\""},
							},
						},
					},
					&actionExpr{
						run: (*parser).call_onThrowExpr_9,
						expr: &seqExpr{
							exprs: []any{
								&litMatcher{val: "%", want: "\"%\""},
								&litMatcher{val: "{", want: "\"{\""},
								&ruleRefExpr{name: "IdentifierName"},
								&ruleRefExpr{name: "EOF"},
							},
						},
					},
				},
			},
		},
		{
			name: "CodeBlock",
			expr: &choiceExpr{
				alternatives: []any{
					&actionExpr{
						run: (*parser).call_onCodeBlock_2,
						expr: &seqExpr{
							exprs: []any{
								&litMatcher{val: "{", want: "\"{\""},
								&ruleRefExpr{name: "Code"},
								&litMatcher{val: "}", want: "\"}\""},
							},
						},
					},
					&actionExpr{
						run: (*parser).call_onCodeBlock_7,
						expr: &seqExpr{
							exprs: []any{
								&litMatcher{val: "{", want: "\"{\""},
								&ruleRefExpr{name: "Code"},
								&ruleRefExpr{name: "EOF"},
							},
						},
					},
				},
			},
		},
		{
			name: "Code",
			expr: &zeroOrMoreExpr{
				expr: &choiceExpr{
					alternatives: []any{
						&oneOrMoreExpr{
							expr: &choiceExpr{
								alternatives: []any{
									&ruleRefExpr{name: "Comment"},
									&ruleRefExpr{name: "CodeStringLiteral"},
									&seqExpr{
										exprs: []any{
											&notExpr{
												expr: &charClassMatcher{
													val:   "[{}]",
													chars: []rune{'{', '}'},
												},
											},
											&ruleRefExpr{name: "SourceChar"},
										},
									},
								},
							},
						},
						&seqExpr{
							exprs: []any{
								&litMatcher{val: "{", want: "\"{\""},
								&ruleRefExpr{name: "Code"},
								&litMatcher{val: "}", want: "\"}\""},
							},
						},
					},
				},
			},
		},
		{
			name: "CodeStringLiteral",
			expr: &choiceExpr{
				alternatives: []any{
					&seqExpr{
						exprs: []any{
							&litMatcher{val: "\"", want: "\"\\\"\""},
							&zeroOrMoreExpr{
								expr: &choiceExpr{
									alternatives: []any{
										&litMatcher{val: "\\\"", want: "\"\\\\\\\"\""},
										&litMatcher{val: "\\\\", want: "\"\\\\\\\\\""},
										&charClassMatcher{
											val:      "[^\"\\r\\n]",
											chars:    []rune{'"', '\r', '\n'},
											inverted: true,
										},
									},
								},
							},
							&litMatcher{val: "\"", want: "\"\\\"\""},
						},
					},
					&seqExpr{
						exprs: []any{
							&litMatcher{val: "`", want: "\"`\""},
							&zeroOrMoreExpr{
								expr: &charClassMatcher{
									val:      "[^`]",
									chars:    []rune{'`'},
									inverted: true,
								},
							},
							&litMatcher{val: "`", want: "\"`\""},
						},
					},
					&seqExpr{
						exprs: []any{
							&litMatcher{val: "'", want: "\"'\""},
							&choiceExpr{
								alternatives: []any{
									&litMatcher{val: "\\'", want: "\"\\\\'\""},
									&litMatcher{val: "\\\\", want: "\"\\\\\\\\\""},
									&oneOrMoreExpr{
										expr: &charClassMatcher{
											val:      "[^']",
											chars:    []rune{'\''},
											inverted: true,
										},
									},
								},
							},
							&litMatcher{val: "'", want: "\"'\""},
						},
					},
				},
			},
		},
		{
			name: "__",
			expr: &zeroOrMoreExpr{
				expr: &choiceExpr{
					alternatives: []any{
						&ruleRefExpr{name: "Whitespace"},
						&ruleRefExpr{name: "EOL"},
						&ruleRefExpr{name: "Comment"},
					},
				},
			},
		},
		{
			name: "_",
			expr: &zeroOrMoreExpr{
				expr: &choiceExpr{
					alternatives: []any{
						&ruleRefExpr{name: "Whitespace"},
						&ruleRefExpr{name: "MultiLineCommentNoLineTerminator"},
					},
				},
			},
		},
		{
			name: "Whitespace",
			expr: &charClassMatcher{
				val:   "[ \\t\\r]",
				chars: []rune{' ', '\t', '\r'},
			},
		},
		{
			name: "EOL",
			expr: &litMatcher{val: "\n", want: "\"\\n\""},
		},
		{
			name: "EOS",
			expr: &choiceExpr{
				alternatives: []any{
					&seqExpr{
						exprs: []any{
							&ruleRefExpr{name: "__"},
							&litMatcher{val: ";", want: "\";\""},
						},
					},
					&seqExpr{
						exprs: []any{
							&ruleRefExpr{name: "_"},
							&zeroOrOneExpr{
								expr: &ruleRefExpr{name: "SingleLineComment"},
							},
							&ruleRefExpr{name: "EOL"},
						},
					},
					&seqExpr{
						exprs: []any{
							&ruleRefExpr{name: "__"},
							&ruleRefExpr{name: "EOF"},
						},
					},
				},
			},
		},
		{
			name: "EOF",
			expr: &notExpr{
				expr: &anyMatcher{},
			},
		},
	},
}

func (p *parser) call_onGrammar_6() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, i any) any {
		return i
		return nil
	})(&p.cur, stack["i"])
}

func (p *parser) call_onGrammar_13() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, r any) any {
		return r
		return nil
	})(&p.cur, stack["r"])
}

func (p *parser) call_onGrammar_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, initializer, rules any) any {
		pos := c.astPos()

		// create the grammar, assign its initializer
		g := ast.NewGrammar(pos)
		if initializer != nil {
			g.Init = initializer.(*ast.CodeBlock)
		}

		rulesSlice := toAnySlice(rules)
		g.Rules = make([]*ast.Rule, len(rulesSlice))
		for i, duo := range rulesSlice {
			g.Rules[i] = duo.(*ast.Rule)
		}

		return g
		return nil
	})(&p.cur, stack["initializer"], stack["rules"])
}

func (p *parser) call_onInitializer_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, code any) any {
		return code
		return nil
	})(&p.cur, stack["code"])
}

func (p *parser) call_onRule_8() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, sl any) any {
		return sl
		return nil
	})(&p.cur, stack["sl"])
}

func (p *parser) call_onRule_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, name, display, expr any) any {
		pos := c.astPos()

		rule := ast.NewRule(pos, name.(*ast.Identifier))
		if display != nil {
			rule.DisplayName = display.(*ast.StringLit)
		}
		rule.Expr = expr.(ast.Expression)

		return rule
		return nil
	})(&p.cur, stack["name"], stack["display"], stack["expr"])
}

func (p *parser) call_onRecoveryExpr_7() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, lbs, ce any) any {
		return []any{lbs, ce}
		return nil
	})(&p.cur, stack["lbs"], stack["ce"])
}

func (p *parser) call_onRecoveryExpr_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, expr, recoverExprs any) any {
		recoverExprSlice := toAnySlice(recoverExprs)
		recover := expr.(ast.Expression)
		for _, sl := range recoverExprSlice {
			pos := c.astPos()
			r := ast.NewRecoveryExpr(pos)
			r.Expr = recover
			r.RecoverExpr = sl.([]any)[1].(ast.Expression)
			r.Labels = sl.([]any)[0].([]ast.FailureLabel)

			recover = r
		}
		return recover
		return nil
	})(&p.cur, stack["expr"], stack["recoverExprs"])
}

func (p *parser) call_onLabels_7() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, id any) any {
		return id
		return nil
	})(&p.cur, stack["id"])
}

func (p *parser) call_onLabels_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, label, labels any) any {
		failureLabels := []ast.FailureLabel{ast.FailureLabel(label.(*ast.Identifier).Val)}
		labelSlice := toAnySlice(labels)
		for _, fl := range labelSlice {
			failureLabels = append(failureLabels, ast.FailureLabel(fl.(*ast.Identifier).Val))
		}
		return failureLabels
		return nil
	})(&p.cur, stack["label"], stack["labels"])
}

func (p *parser) call_onChoiceExpr_7() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, ase any) any {
		return ase
		return nil
	})(&p.cur, stack["ase"])
}

func (p *parser) call_onChoiceExpr_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, first, rest any) any {
		restSlice := toAnySlice(rest)
		if len(restSlice) == 0 {
			return first
		}

		pos := c.astPos()
		choice := ast.NewChoiceExpr(pos)
		choice.Alternatives = []ast.Expression{first.(ast.Expression)}
		for _, sl := range restSlice {
			choice.Alternatives = append(choice.Alternatives, sl.(ast.Expression))
		}
		return choice
		return nil
	})(&p.cur, stack["first"], stack["rest"])
}

func (p *parser) call_onActionSeqExpr_7() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, ae any) any {
		return ae
		return nil
	})(&p.cur, stack["ae"])
}

func (p *parser) call_onActionSeqExpr_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, first, rest any) any {
		restSlice := toAnySlice(rest)
		if len(restSlice) == 0 {
			return first
		}
		seq := ast.NewSeqExpr(c.astPos())
		seq.Exprs = []ast.Expression{first.(ast.Expression)}
		for _, sl := range restSlice {
			seq.Exprs = append(seq.Exprs, sl.(ast.Expression))
		}
		return seq
		return nil
	})(&p.cur, stack["first"], stack["rest"])
}

func (p *parser) call_onActionExpr_8() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, cb any) any {
		return cb
		return nil
	})(&p.cur, stack["cb"])
}

func (p *parser) call_onActionExpr_2() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, expr, code any) any {
		if code == nil {
			return expr
		}

		pos := c.astPos()
		act := ast.NewActionExpr(pos)
		act.Expr = expr.(ast.Expression)
		act.Code = code.(*ast.CodeBlock)

		return act
		return nil
	})(&p.cur, stack["expr"], stack["code"])
}

func (p *parser) call_onActionExpr_13() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, code any) any {
		state := ast.NewCodeExpr(c.astPos())
		state.Code = code.(*ast.CodeBlock)
		return state
		return nil
	})(&p.cur, stack["code"])
}

func (p *parser) call_onSeqExpr_7() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, le any) any {
		return le
		return nil
	})(&p.cur, stack["le"])
}

func (p *parser) call_onSeqExpr_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, first, rest any) any {
		restSlice := toAnySlice(rest)
		if len(restSlice) == 0 {
			return first
		}
		seq := ast.NewSeqExpr(c.astPos())
		seq.Exprs = []ast.Expression{first.(ast.Expression)}
		for _, sl := range restSlice {
			seq.Exprs = append(seq.Exprs, sl.(ast.Expression))
		}
		return seq
		return nil
	})(&p.cur, stack["first"], stack["rest"])
}

func (p *parser) call_onLabeledExpr_2() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, label, expr any) any {
		pos := c.astPos()
		lab := ast.NewLabeledExpr(pos)
		lab.Label = label.(*ast.Identifier)
		lab.Expr = expr.(ast.Expression)
		lab.TextCapture = true
		return lab
		return nil
	})(&p.cur, stack["label"], stack["expr"])
}

func (p *parser) call_onLabeledExpr_15() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, label, expr any) any {
		pos := c.astPos()
		lab := ast.NewLabeledExpr(pos)
		lab.Label = label.(*ast.Identifier)
		lab.Expr = expr.(ast.Expression)
		return lab
		return nil
	})(&p.cur, stack["label"], stack["expr"])
}

func (p *parser) call_onPrefixedExpr_2() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, op, expr any) any {
		pos := c.astPos()
		opStr := op.(string)
		if opStr == "&" {
			and := ast.NewAndExpr(pos)
			and.Expr = expr.(ast.Expression)
			return and
		}
		if opStr == "&&" {
			and := ast.NewAndExpr(pos)
			and.Expr = expr.(ast.Expression)
			and.Logical = true
			return and
		}
		not := ast.NewNotExpr(pos)
		not.Expr = expr.(ast.Expression)
		if opStr == "!!" {
			not.Logical = true
		}
		return not
		return nil
	})(&p.cur, stack["op"], stack["expr"])
}

func (p *parser) call_onPrefixedOp_1() any {
	return (func(c *current) any {
		return string(c.text)
		return nil
	})(&p.cur)
}

func (p *parser) call_onSuffixedExpr_2() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, expr, op any) any {
		pos := c.astPos()
		opStr := op.(string)
		switch opStr {
		case "?":
			zero := ast.NewZeroOrOneExpr(pos)
			zero.Expr = expr.(ast.Expression)
			return zero
		case "*":
			zero := ast.NewZeroOrMoreExpr(pos)
			zero.Expr = expr.(ast.Expression)
			return zero
		case "+":
			one := ast.NewOneOrMoreExpr(pos)
			one.Expr = expr.(ast.Expression)
			return one
		default:
			p.addErr(errors.New("unknown operator: " + opStr))
			return nil
		}
		return nil
	})(&p.cur, stack["expr"], stack["op"])
}

func (p *parser) call_onSuffixedOp_1() any {
	return (func(c *current) any {
		return string(c.text)
		return nil
	})(&p.cur)
}

func (p *parser) call_onPrimaryExpr_7() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, expr any) any {
		return expr
		return nil
	})(&p.cur, stack["expr"])
}

func (p *parser) call_onRuleRefExpr_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, name any) any {
		ref := ast.NewRuleRefExpr(c.astPos())
		ref.Name = name.(*ast.Identifier)
		return ref
		return nil
	})(&p.cur, stack["name"])
}

func (p *parser) call_onSemanticPredExpr_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, op, code any) any {
		switch op.(string) {
		case "&":
			and := ast.NewAndCodeExpr(c.astPos())
			and.Code = code.(*ast.CodeBlock)
			return and

		case "*":
			ce := ast.NewCodeExpr(c.astPos())
			ce.Code = code.(*ast.CodeBlock)
			ce.NotSkip = true
			return ce

		// case "!":
		default:
			not := ast.NewNotCodeExpr(c.astPos())
			not.Code = code.(*ast.CodeBlock)
			return not

		}
		return nil
	})(&p.cur, stack["op"], stack["code"])
}

func (p *parser) call_onSemanticPredOp_1() any {
	return (func(c *current) any {
		return string(c.text)
		return nil
	})(&p.cur)
}

func (p *parser) call_onIdentifier_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, ident any) any {
		astIdent := ast.NewIdentifier(c.astPos(), string(c.text))
		if reservedWords[astIdent.Val] {
			p.addErr(errors.New("identifier is a reserved word"))
			return astIdent
		}
		return astIdent
		return nil
	})(&p.cur, stack["ident"])
}

func (p *parser) call_onIdentifierName_1() any {
	return (func(c *current) any {
		return ast.NewIdentifier(c.astPos(), string(c.text))
		return nil
	})(&p.cur)
}

func (p *parser) call_onLitMatcher_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, lit, ignore any) any {
		rawStr := lit.(*ast.StringLit).Val
		s, err := strconv.Unquote(rawStr)
		if err != nil {
			// an invalid string literal raises an error in the escape rules,
			// so simply replace the literal with an empty string here to
			// avoid a cascade of errors.
			s = ""
		}
		m := ast.NewLitMatcher(c.astPos(), s)
		m.IgnoreCase = ignore != nil
		return m
		return nil
	})(&p.cur, stack["lit"], stack["ignore"])
}

func (p *parser) call_onStringLiteral_2() any {
	return (func(c *current) any {
		return ast.NewStringLit(c.astPos(), string(c.text))
		return nil
	})(&p.cur)
}

func (p *parser) call_onStringLiteral_18() any {
	return (func(c *current) any {
		p.addErr(errors.New("string literal not terminated"))
		return ast.NewStringLit(c.astPos(), "``")
		return nil
	})(&p.cur)
}

func (p *parser) call_onDoubleStringEscape_5() any {
	return (func(c *current) any {
		p.addErr(errors.New("invalid escape character"))
		return nil
	})(&p.cur)
}

func (p *parser) call_onSingleStringEscape_5() any {
	return (func(c *current) any {
		p.addErr(errors.New("invalid escape character"))
		return nil
	})(&p.cur)
}

func (p *parser) call_onOctalEscape_6() any {
	return (func(c *current) any {
		p.addErr(errors.New("invalid octal escape"))
		return nil
	})(&p.cur)
}

func (p *parser) call_onHexEscape_6() any {
	return (func(c *current) any {
		p.addErr(errors.New("invalid hexadecimal escape"))
		return nil
	})(&p.cur)
}

func (p *parser) call_onLongUnicodeEscape_2() any {
	return (func(c *current) any {
		val, err := validateUnicodeEscape(string(c.text), "invalid Unicode escape")
		if err != nil {
			p.addErr(err)
		}
		return val
		return nil
	})(&p.cur)
}

func (p *parser) call_onLongUnicodeEscape_13() any {
	return (func(c *current) any {
		p.addErr(errors.New("invalid Unicode escape"))
		return nil
	})(&p.cur)
}

func (p *parser) call_onShortUnicodeEscape_2() any {
	return (func(c *current) any {
		val, err := validateUnicodeEscape(string(c.text), "invalid Unicode escape")
		if err != nil {
			p.addErr(err)
		}
		return val
		return nil
	})(&p.cur)
}

func (p *parser) call_onShortUnicodeEscape_9() any {
	return (func(c *current) any {
		p.addErr(errors.New("invalid Unicode escape"))
		return nil
	})(&p.cur)
}

func (p *parser) call_onCharClassMatcher_2() any {
	return (func(c *current) any {
		pos := c.astPos()
		cc := ast.NewCharClassMatcher(pos, string(c.text))
		return cc
		return nil
	})(&p.cur)
}

func (p *parser) call_onCharClassMatcher_15() any {
	return (func(c *current) any {
		p.addErr(errors.New("character class not terminated"))
		return ast.NewCharClassMatcher(c.astPos(), "[]")
		return nil
	})(&p.cur)
}

func (p *parser) call_onCharClassEscape_5() any {
	return (func(c *current) any {
		p.addErr(errors.New("invalid escape character"))
		return nil
	})(&p.cur)
}

func (p *parser) call_onUnicodeClassEscape_5() any {
	return (func(c *current) any {
		p.addErr(errors.New("invalid Unicode class escape"))
		return nil
	})(&p.cur)
}

func (p *parser) call_onUnicodeClassEscape_13() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, ident any) any {
		if !unicodeClasses[ident.(*ast.Identifier).Val] {
			p.addErr(errors.New("invalid Unicode class escape"))
		}
		return nil
	})(&p.cur, stack["ident"])
}

func (p *parser) call_onUnicodeClassEscape_19() any {
	return (func(c *current) any {
		p.addErr(errors.New("Unicode class not terminated"))
		return nil
	})(&p.cur)
}

func (p *parser) call_onAnyMatcher_1() any {
	return (func(c *current) any {
		any := ast.NewAnyMatcher(c.astPos(), ".")
		return any
		return nil
	})(&p.cur)
}

func (p *parser) call_onThrowExpr_2() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, label any) any {
		t := ast.NewThrowExpr(c.astPos())
		t.Label = label.(*ast.Identifier).Val
		return t
		return nil
	})(&p.cur, stack["label"])
}

func (p *parser) call_onThrowExpr_9() any {
	return (func(c *current) any {
		p.addErr(errors.New("throw expression not terminated"))
		return nil
	})(&p.cur)
}

func (p *parser) call_onCodeBlock_2() any {
	return (func(c *current) any {
		pos := c.astPos()
		cb := ast.NewCodeBlock(pos, string(c.text))
		return cb
		return nil
	})(&p.cur)
}

func (p *parser) call_onCodeBlock_7() any {
	return (func(c *current) any {
		p.addErr(errors.New("code block not terminated"))
		return nil
	})(&p.cur)
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// remove generic because it can't be compiled by gopherjs
type parserStack struct {
	data  []savepoint
	index int
	size  int
}

func (ss *parserStack) init(size int) {
	ss.index = -1
	ss.data = make([]savepoint, size)
	ss.size = size
}

func (ss *parserStack) push(v *savepoint) {
	ss.index += 1
	if ss.index == ss.size {
		ss.data = append(ss.data, *v)
		ss.size = len(ss.data)
	} else {
		ss.data[ss.index] = *v
	}
}

func (ss *parserStack) pop() *savepoint {
	ref := &ss.data[ss.index]
	ss.index--
	return ref
}

func (ss *parserStack) top() *savepoint {
	return &ss.data[ss.index]
}

// option is a function that can set an option on the parser. It returns
// the previous setting as an option.
type option func(*parser) option

func noMatchErrorFormatter(fn func(position, []byte, []string) error) option {
	return func(p *parser) option {
		old := p.noMatchErrorFormatter
		p.noMatchErrorFormatter = fn
		return noMatchErrorFormatter(old)
	}
}

// statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func statistics(stats *Stats, choiceNoMatch string) option {
	return func(p *parser) option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return statistics(oldStats, oldChoiceNoMatch)
	}
}

// debug creates an option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func debug(b bool) option {
	return func(p *parser) option {
		old := p.debug
		p.debug = b
		return debug(old)
	}
}

func memoized(b bool) option {
	return func(p *parser) option {
		old := p.memoized
		p.memoized = b
		return memoized(old)
	}
}

// Parse parses the data from b using filename as information in the
// error messages.
func parse(filename string, b []byte, opts ...option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match
	data *ParserCustomData
}

// the AST types...

// nolint: structcheck
type grammar struct {
	rules []*rule
}

// nolint: structcheck
type rule struct {
	name        string
	displayName string
	expr        any
	varExists   bool
}

// nolint: structcheck
type choiceExpr struct {
	alternatives []any
}

// nolint: structcheck
type actionExpr struct {
	expr any
	run  func(*parser) any
}

// nolint: structcheck
type recoveryExpr struct {
	expr         any
	recoverExpr  any
	failureLabel []string
}

// nolint: structcheck
type seqExpr struct {
	exprs []any
}

// nolint: structcheck
type throwExpr struct {
	label string
}

// nolint: structcheck
type labeledExpr struct {
	label       string
	expr        any
	textCapture bool
}

// nolint: structcheck
type expr struct {
	expr any
}

type (
	andExpr        expr // nolint: structcheck
	notExpr        expr // nolint: structcheck
	andLogicalExpr expr // nolint: structcheck
	notLogicalExpr expr // nolint: structcheck
	zeroOrOneExpr  expr // nolint: structcheck
	zeroOrMoreExpr expr // nolint: structcheck
	oneOrMoreExpr  expr // nolint: structcheck
)

// nolint: structcheck
type ruleRefExpr struct {
	name string
}

// nolint: structcheck
type andCodeExpr struct {
	run func(*parser) bool
}

// nolint: structcheck
type notCodeExpr struct {
	run func(*parser) bool
}

// nolint: structcheck
type litMatcher struct {
	val        string
	ignoreCase bool
	want       string
}

// nolint: structcheck
type codeExpr struct {
	run     func(*parser) any
	notSkip bool
}

// nolint: structcheck
type charClassMatcher struct {
	val        string
	chars      []rune
	ranges     []rune
	classes    []*unicode.RangeTable
	ignoreCase bool
	inverted   bool
}

type anyMatcher struct{} // nolint: structcheck

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// nolint: structcheck,deadcode
type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

// nolint: varcheck
const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the exprType of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The exprType of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

// nolint: structcheck,maligned
type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth    int
	recover  bool
	memoized bool
	debug    bool

	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo1 map[int]map[any]*resultTuple
	memo2 map[int]map[any]*resultTuple

	// rules table, maps the rule identifier to the rule node
	rules      map[string]*rule
	rulesArray []*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool
	noMatchErrorFormatter func(position, []byte, []string) error

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any

	_errPos *position
	// skip code stack
	scStack []bool
	// save point stack
	spStack parserStack
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  false,
		cur: current{
			data: &ParserCustomData{},
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		memo1:           map[int]map[any]*resultTuple{},
		memo2:           map[int]map[any]*resultTuple{},
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: "Grammar",
		scStack:    []bool{false},
	}

	p.spStack.init(5)
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []option) {
	for _, opt := range opts {
		opt(p)
	}
}

// setCustomData to the parser.
func (p *parser) setCustomData(data *ParserCustomData) {
	p.cur.data = data
}

func (p *parser) checkSkipCode() bool {
	return p.scStack[len(p.scStack)-1]
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	if p._errPos != nil {
		p.addErrAt(err, *p._errPos, []string{})
	} else {
		p.addErrAt(err, p.pt.position, []string{})
	}
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) buildNoMatchError(pos position, expected []string) error {
	if p.noMatchErrorFormatter != nil {
		if err := p.noMatchErrorFormatter(pos, p.data, expected); err != nil {
			return err
		}
	}

	return errors.New("no match found, expected: " + listJoin(expected, ", ", "or"))
}

func (p *parser) failAt(fail bool, pos *position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = *pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt *savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = *pt
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start *savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFromOffset(offset int) []byte {
	return p.data[offset:p.pt.position.offset]
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

// nolint: gocyclo
func (p *parser) parse(grammar *grammar) (val any, err error) {
	if grammar == nil {
		grammar = g
	}
	if len(grammar.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	p.rulesArray = grammar.rules
	p.buildRulesTable(grammar)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(p.buildNoMatchError(p.maxFailPos, expected), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = &p.pt
	)

	val, ok = p.parseRule(rule)

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	val, ok := p.parseExpr(expr)
	return val, ok
}

// nolint: gocyclo
func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	skipCode := p.checkSkipCode()
	memo := p.memo1
	if skipCode {
		memo = p.memo2
	}

	setMemoized := func(pos int, expr any, val resultTuple) {
		if !p.memoized {
			return
		}
		if memo[pos] == nil {
			memo[pos] = map[any]*resultTuple{}
		}
		memo[pos][expr] = &val
	}

	if p.memoized {
		getMemoized := func(expr any) *resultTuple {
			pos := p.pt.offset
			if memo[pos] == nil {
				return nil
			}
			return memo[pos][expr]
		}

		if m := getMemoized(expr); m != nil {
			p.restore(&m.end)
			return m.v, m.b
		}
	}

	pos := p.pt.offset

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *andLogicalExpr:
		val, ok = p.parseAndLogicalExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *codeExpr:
		val, ok = p.parseCodeExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *notLogicalExpr:
		val, ok = p.parseNotLogicalExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}

	setMemoized(pos, expr, resultTuple{val, ok, p.pt})
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	if p.checkSkipCode() {
		_, ok := p.parseExprWrap(act.expr)
		return nil, ok
	}

	p.spStack.push(&p.pt)
	val, ok := p.parseExprWrap(act.expr)
	start := p.spStack.pop()

	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		p._errPos = &start.position
		actVal := act.run(p)
		p._errPos = nil
		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(&p.spStack.data[p.spStack.index+1])))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	ok := and.run(p)
	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	return p.parseAndExprBase(and, false)
}

func (p *parser) parseAndLogicalExpr(and *andLogicalExpr) (any, bool) {
	return p.parseAndExprBase((*andExpr)(and), true)
}

func (p *parser) parseAndExprBase(and *andExpr, logical bool) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt

	p.scStack = append(p.scStack, true)
	_, ok := p.parseExprWrap(and.expr)
	p.scStack = p.scStack[:len(p.scStack)-1]

	matchedOffset := p.pt.offset
	p.restore(&pt)

	if logical {
		return nil, ok && p.pt.offset != matchedOffset
	}
	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, &p.pt.position, ".")
		return nil, false
	}
	p.failAt(true, &p.pt.position, ".")
	p.read()
	return nil, true
}

// nolint: gocyclo
func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, &p.pt.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, &p.pt.position, chr.val)
				return nil, false
			}
			p.failAt(true, &p.pt.position, chr.val)
			p.read()
			return nil, true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, &p.pt.position, chr.val)
				return nil, false
			}
			p.failAt(true, &p.pt.position, chr.val)
			p.read()
			return nil, true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, &p.pt.position, chr.val)
				return nil, false
			}
			p.failAt(true, &p.pt.position, chr.val)
			p.read()
			return nil, true
		}
	}

	if chr.inverted {
		p.failAt(true, &p.pt.position, chr.val)
		p.read()
		return nil, true
	}
	p.failAt(false, &p.pt.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	// choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	choiceIdent := fmt.Sprintf("%s", p.rstack[len(p.rstack)-1].name)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		val, ok := p.parseExprWrap(alt)
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	startOffset := p.pt.position.offset
	var val any
	var ok bool
	val, ok = p.parseExprWrap(lab.expr)
	if ok && lab.label != "" && !p.checkSkipCode() {
		m := p.vstack[len(p.vstack)-1]
		if lab.textCapture {
			m[lab.label] = string(p.sliceFromOffset(startOffset))
		} else {
			m[lab.label] = val
		}
	}
	return val, ok
}

func (p *parser) parseCodeExpr(code *codeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCodeExpr"))
	}

	if !code.notSkip && p.checkSkipCode() {
		return nil, true
	}
	return code.run(p), true
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, &start.position, lit.want)
			p.restore(&start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, &start.position, lit.want)
	return nil, true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	ok := not.run(p)
	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	return p.parseNotExprBase(not, false)
}

func (p *parser) parseNotLogicalExpr(not *notLogicalExpr) (any, bool) {
	return p.parseNotExprBase((*notExpr)(not), true)
}

func (p *parser) parseNotExprBase(not *notExpr, logical bool) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	p.maxFailInvertExpected = !p.maxFailInvertExpected

	p.scStack = append(p.scStack, true)
	_, ok := p.parseExprWrap(not.expr)
	p.scStack = p.scStack[:len(p.scStack)-1]

	p.maxFailInvertExpected = !p.maxFailInvertExpected
	matchedOffset := p.pt.offset
	p.restore(&pt)

	if logical {
		return nil, !ok && p.pt.offset != matchedOffset
	}
	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any
	var matched bool
	for {
		val, ok := p.parseExprWrap(expr.expr)
		if !ok {
			if len(vals) > 0 {
				return vals, matched
			}
			return nil, matched
		}
		matched = true
		if val != nil {
			vals = append(vals, val)
		}
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	var vals []any
	notSkipCode := p.checkSkipCode()

	pt := p.pt
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restore(&pt)
			return nil, false
		}
		if notSkipCode && val != nil {
			vals = append(vals, val)
		}
	}
	if len(vals) > 0 {
		return vals, true
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}
	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any
	for {
		val, ok := p.parseExprWrap(expr.expr)
		if !ok {
			if len(vals) > 0 {
				return vals, true
			}
			return nil, true
		}
		if val != nil {
			vals = append(vals, val)
		}
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	val, _ := p.parseExprWrap(expr.expr)
	// whether it matched or not, consider it a match
	return val, true
}
