// Code generated by pigeon; DO NOT EDIT.

//nolint:unreachable
package main

import (
	"bytes"
	"errors"
	"fmt"
	"math"
	"sort"
	"strconv"
	"strings"
	"unicode"
	"unicode/utf8"
)

type ParserCustomData struct {
	Indentation int
}

func toAnySlice(v any) []any {
	if v == nil {
		return nil
	}
	return v.([]any)
}

var g = &grammar{
	rules: []*rule{
		{
			name:      "Input",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onInput_1,
				expr: &seqExpr{
					exprs: []any{
						&andCodeExpr{run: (*parser).call_onInput_3},
						&labeledExpr{
							label: "s",
							expr:  &ruleIRefExpr{index: 1 /* Statements */},
						},
						&labeledExpr{
							label: "r",
							expr:  &ruleIRefExpr{index: 3 /* ReturnOp */},
						},
						&ruleIRefExpr{index: 15 /* EOF */},
					},
				},
			},
		},
		{
			name:      "Statements",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onStatements_1,
				expr: &labeledExpr{
					label: "s",
					expr: &oneOrMoreExpr{
						expr: &ruleIRefExpr{index: 2 /* Line */},
					},
				},
			},
		},
		{
			name:      "Line",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onLine_1,
				expr: &seqExpr{
					exprs: []any{
						&ruleIRefExpr{index: 16 /* INDENTATION */},
						&labeledExpr{
							label: "s",
							expr:  &ruleIRefExpr{index: 4 /* Statement */},
						},
					},
				},
			},
		},
		{
			name:      "ReturnOp",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onReturnOp_1,
				expr: &seqExpr{
					exprs: []any{
						&litMatcher{val: "return", want: "\"return\""},
						&ruleIRefExpr{index: 12 /* _ */},
						&labeledExpr{
							label: "arg",
							expr:  &ruleIRefExpr{index: 10 /* Identifier */},
						},
						&ruleIRefExpr{index: 13 /* EOL */},
					},
				},
			},
		},
		{
			name:      "Statement",
			varExists: true,
			expr: &choiceExpr{
				alternatives: []any{
					&actionExpr{
						run: (*parser).call_onStatement_2,
						expr: &seqExpr{
							exprs: []any{
								&labeledExpr{
									label: "s",
									expr:  &ruleIRefExpr{index: 5 /* Assignment */},
								},
								&ruleIRefExpr{index: 13 /* EOL */},
							},
						},
					},
					&actionExpr{
						run: (*parser).call_onStatement_7,
						expr: &seqExpr{
							exprs: []any{
								&litMatcher{val: "if", want: "\"if\""},
								&ruleIRefExpr{index: 12 /* _ */},
								&labeledExpr{
									label: "arg",
									expr:  &ruleIRefExpr{index: 6 /* LogicalExpression */},
								},
								&zeroOrOneExpr{
									expr: &ruleIRefExpr{index: 12 /* _ */},
								},
								&litMatcher{val: ":", want: "\":\""},
								&ruleIRefExpr{index: 13 /* EOL */},
								&ruleIRefExpr{index: 17 /* INDENT */},
								&labeledExpr{
									label: "s",
									expr:  &ruleIRefExpr{index: 1 /* Statements */},
								},
								&ruleIRefExpr{index: 18 /* DEDENT */},
							},
						},
					},
				},
			},
		},
		{
			name:      "Assignment",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onAssignment_1,
				expr: &seqExpr{
					exprs: []any{
						&labeledExpr{
							label: "lvalue",
							expr:  &ruleIRefExpr{index: 10 /* Identifier */},
						},
						&zeroOrOneExpr{
							expr: &ruleIRefExpr{index: 12 /* _ */},
						},
						&litMatcher{val: "=", want: "\"=\""},
						&zeroOrOneExpr{
							expr: &ruleIRefExpr{index: 12 /* _ */},
						},
						&labeledExpr{
							label: "rvalue",
							expr:  &ruleIRefExpr{index: 7 /* AdditiveExpression */},
						},
					},
				},
			},
		},
		{
			name:      "LogicalExpression",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onLogicalExpression_1,
				expr: &labeledExpr{
					label: "arg",
					expr:  &ruleIRefExpr{index: 8 /* PrimaryExpression */},
				},
			},
		},
		{
			name:      "AdditiveExpression",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onAdditiveExpression_1,
				expr: &seqExpr{
					exprs: []any{
						&labeledExpr{
							label: "arg",
							expr:  &ruleIRefExpr{index: 8 /* PrimaryExpression */},
						},
						&labeledExpr{
							label: "rest",
							expr: &zeroOrMoreExpr{
								expr: &actionExpr{
									run: (*parser).call_onAdditiveExpression_7,
									expr: &seqExpr{
										exprs: []any{
											&ruleIRefExpr{index: 12 /* _ */},
											&labeledExpr{
												label: "op",
												expr:  &ruleIRefExpr{index: 11 /* AddOp */},
											},
											&ruleIRefExpr{index: 12 /* _ */},
											&labeledExpr{
												label: "r",
												expr:  &ruleIRefExpr{index: 8 /* PrimaryExpression */},
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name:      "PrimaryExpression",
			varExists: true,
			expr: &actionExpr{
				run: (*parser).call_onPrimaryExpression_1,
				expr: &labeledExpr{
					label: "arg",
					expr: &choiceExpr{
						alternatives: []any{
							&ruleIRefExpr{index: 9 /* Integer */},
							&ruleIRefExpr{index: 10 /* Identifier */},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			expr: &actionExpr{
				run: (*parser).call_onInteger_1,
				expr: &oneOrMoreExpr{
					expr: &charClassMatcher{
						val:    "[0-9]",
						ranges: []rune{'0', '9'},
					},
				},
			},
		},
		{
			name: "Identifier",
			expr: &actionExpr{
				run: (*parser).call_onIdentifier_1,
				expr: &seqExpr{
					exprs: []any{
						&charClassMatcher{
							val:    "[a-zA-Z]",
							ranges: []rune{'a', 'z', 'A', 'Z'},
						},
						&zeroOrMoreExpr{
							expr: &charClassMatcher{
								val:    "[a-zA-Z0-9]",
								ranges: []rune{'a', 'z', 'A', 'Z', '0', '9'},
							},
						},
					},
				},
			},
		},
		{
			name: "AddOp",
			expr: &actionExpr{
				run: (*parser).call_onAddOp_1,
				expr: &choiceExpr{
					alternatives: []any{
						&litMatcher{val: "+", want: "\"+\""},
						&litMatcher{val: "-", want: "\"-\""},
					},
				},
			},
		},
		{
			name: "_",
			expr: &oneOrMoreExpr{
				expr: &charClassMatcher{
					val:   "[ \\t]",
					chars: []rune{' ', '\t'},
				},
			},
		},
		{
			name: "EOL",
			expr: &seqExpr{
				exprs: []any{
					&zeroOrOneExpr{
						expr: &ruleIRefExpr{index: 12 /* _ */},
					},
					&zeroOrOneExpr{
						expr: &ruleIRefExpr{index: 14 /* Comment */},
					},
					&choiceExpr{
						alternatives: []any{
							&litMatcher{val: "\r\n", want: "\"\\r\\n\""},
							&litMatcher{val: "\n\r", want: "\"\\n\\r\""},
							&litMatcher{val: "\r", want: "\"\\r\""},
							&litMatcher{val: "\n", want: "\"\\n\""},
							&ruleIRefExpr{index: 15 /* EOF */},
						},
					},
				},
			},
		},
		{
			name: "Comment",
			expr: &seqExpr{
				exprs: []any{
					&litMatcher{val: "//", want: "\"//\""},
					&zeroOrMoreExpr{
						expr: &charClassMatcher{
							val:      "[^\\r\\n]",
							chars:    []rune{'\r', '\n'},
							inverted: true,
						},
					},
				},
			},
		},
		{
			name: "EOF",
			expr: &notExpr{
				expr: &anyMatcher{},
			},
		},
		{
			name:      "INDENTATION",
			varExists: true,
			expr: &seqExpr{
				exprs: []any{
					&notExpr{
						expr: &seqExpr{
							exprs: []any{
								&labeledExpr{
									label: "spaces",
									expr: &zeroOrMoreExpr{
										expr: &litMatcher{val: " ", want: "\" \""},
									},
									textCapture: true,
								},
								&andCodeExpr{run: (*parser).call_onINDENTATION_7},
							},
						},
					},
					&zeroOrMoreExpr{
						expr: &litMatcher{val: " ", want: "\" \""},
					},
				},
			},
		},
		{
			name: "INDENT",
			expr: &codeExpr{
				run: (*parser).call_onINDENT_1,
			},
		},
		{
			name: "DEDENT",
			expr: &codeExpr{
				run: (*parser).call_onDEDENT_1,
			},
		},
	},
}

func (p *parser) call_onInput_3() bool {
	return (func(c *current) bool {
		c.data.Indentation = 0
		return true
	})(&p.cur)
}

func (p *parser) call_onInput_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, s, r any) any {
		return newProgramNode(s.(StatementsNode), r.(ReturnNode))
		return nil
	})(&p.cur, stack["s"], stack["r"])
}

func (p *parser) call_onStatements_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, s any) any {
		return newStatementsNode(s)
		return nil
	})(&p.cur, stack["s"])
}

func (p *parser) call_onLine_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, s any) any {
		return s
		return nil
	})(&p.cur, stack["s"])
}

func (p *parser) call_onReturnOp_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, arg any) any {
		return newReturnNode(arg.(IdentifierNode))
		return nil
	})(&p.cur, stack["arg"])
}

func (p *parser) call_onStatement_2() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, s any) any {
		return s.(AssignmentNode)
		return nil
	})(&p.cur, stack["s"])
}

func (p *parser) call_onStatement_7() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, arg, s any) any {
		return newIfNode(arg.(LogicalExpressionNode), s.(StatementsNode))
		return nil
	})(&p.cur, stack["arg"], stack["s"])
}

func (p *parser) call_onAssignment_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, lvalue, rvalue any) any {
		return newAssignmentNode(lvalue.(IdentifierNode), rvalue.(AdditiveExpressionNode))
		return nil
	})(&p.cur, stack["lvalue"], stack["rvalue"])
}

func (p *parser) call_onLogicalExpression_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, arg any) any {
		return newLogicalExpressionNode(arg.(PrimaryExpressionNode))
		return nil
	})(&p.cur, stack["arg"])
}

func (p *parser) call_onAdditiveExpression_7() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, op, r any) any {
		return []any{op, r}
		return nil
	})(&p.cur, stack["op"], stack["r"])
}

func (p *parser) call_onAdditiveExpression_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, arg, rest any) any {
		return newAdditiveExpressionNode(arg.(PrimaryExpressionNode), rest)
		return nil
	})(&p.cur, stack["arg"], stack["rest"])
}

func (p *parser) call_onPrimaryExpression_1() any {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, arg any) any {
		return newPrimaryExpressionNode(arg)
		return nil
	})(&p.cur, stack["arg"])
}

func (p *parser) call_onInteger_1() any {
	return (func(c *current) any {
		val, err := newIntegerNode(string(c.text))
		if err != nil {
			p.addErr(err)
		}
		return val
		return nil
	})(&p.cur)
}

func (p *parser) call_onIdentifier_1() any {
	return (func(c *current) any {
		return newIdentifierNode(string(c.text))
		return nil
	})(&p.cur)
}

func (p *parser) call_onAddOp_1() any {
	return (func(c *current) any {
		return string(c.text)
		return nil
	})(&p.cur)
}

func (p *parser) call_onINDENTATION_7() bool {
	stack := p.vstack[len(p.vstack)-1]
	return (func(c *current, spaces any) bool {
		return len(spaces.(string)) != c.data.Indentation
	})(&p.cur, stack["spaces"])
}

func (p *parser) call_onINDENT_1() any {
	return (func(c *current) any {
		c.data.Indentation += 4
		return nil
	})(&p.cur)
}

func (p *parser) call_onDEDENT_1() any {
	return (func(c *current) any {
		c.data.Indentation -= 4
		return nil
	})(&p.cur)
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// remove generic because it can't be compiled by gopherjs
type parserStack struct {
	data  []savepoint
	index int
	size  int
}

func (ss *parserStack) init(size int) {
	ss.index = -1
	ss.data = make([]savepoint, size)
	ss.size = size
}

func (ss *parserStack) push(v *savepoint) {
	ss.index += 1
	if ss.index == ss.size {
		ss.data = append(ss.data, *v)
		ss.size = len(ss.data)
	} else {
		ss.data[ss.index] = *v
	}
}

func (ss *parserStack) pop() *savepoint {
	ref := &ss.data[ss.index]
	ss.index--
	return ref
}

func (ss *parserStack) top() *savepoint {
	return &ss.data[ss.index]
}

// option is a function that can set an option on the parser. It returns
// the previous setting as an option.
type option func(*parser) option

// Parse parses the data from b using filename as information in the
// error messages.
func parse(filename string, b []byte, opts ...option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match
	data *ParserCustomData
}

// the AST types...

// nolint: structcheck
type grammar struct {
	rules []*rule
}

// nolint: structcheck
type rule struct {
	name        string
	displayName string
	expr        any
	varExists   bool
}

// nolint: structcheck
type choiceExpr struct {
	alternatives []any
}

// nolint: structcheck
type actionExpr struct {
	expr any
	run  func(*parser) any
}

// nolint: structcheck
type recoveryExpr struct {
	expr         any
	recoverExpr  any
	failureLabel []string
}

// nolint: structcheck
type seqExpr struct {
	exprs []any
}

// nolint: structcheck
type throwExpr struct {
	label string
}

// nolint: structcheck
type labeledExpr struct {
	label       string
	expr        any
	textCapture bool
}

// nolint: structcheck
type expr struct {
	expr any
}

type (
	andExpr        expr // nolint: structcheck
	notExpr        expr // nolint: structcheck
	andLogicalExpr expr // nolint: structcheck
	notLogicalExpr expr // nolint: structcheck
	zeroOrOneExpr  expr // nolint: structcheck
	zeroOrMoreExpr expr // nolint: structcheck
	oneOrMoreExpr  expr // nolint: structcheck
)

// nolint: structcheck
type ruleRefExpr struct {
	name string
}

// nolint: structcheck
type ruleIRefExpr struct {
	index int
}

// nolint: structcheck
type andCodeExpr struct {
	run func(*parser) bool
}

// nolint: structcheck
type notCodeExpr struct {
	run func(*parser) bool
}

// nolint: structcheck
type litMatcher struct {
	val        string
	ignoreCase bool
	want       string
}

// nolint: structcheck
type codeExpr struct {
	run     func(*parser) any
	notSkip bool
}

// nolint: structcheck
type charClassMatcher struct {
	val        string
	chars      []rune
	ranges     []rune
	classes    []*unicode.RangeTable
	ignoreCase bool
	inverted   bool
}

type anyMatcher struct{} // nolint: structcheck

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// nolint: structcheck,deadcode
type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

// nolint: varcheck
const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the exprType of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The exprType of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

// nolint: structcheck,maligned
type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool

	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo1 map[int]map[any]*resultTuple
	memo2 map[int]map[any]*resultTuple

	// rules table, maps the rule identifier to the rule node
	rules      map[string]*rule
	rulesArray []*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any

	_errPos *position
	// skip code stack
	scStack []bool
	// save point stack
	spStack parserStack
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  false,
		cur: current{
			data: &ParserCustomData{},
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		memo1:           map[int]map[any]*resultTuple{},
		memo2:           map[int]map[any]*resultTuple{},
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: "Input",
		scStack:    []bool{false},
	}

	p.spStack.init(5)
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []option) {
	for _, opt := range opts {
		opt(p)
	}
}

// setCustomData to the parser.
func (p *parser) setCustomData(data *ParserCustomData) {
	p.cur.data = data
}

func (p *parser) checkSkipCode() bool {
	return p.scStack[len(p.scStack)-1]
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) addErr(err error) {
	if p._errPos != nil {
		p.addErrAt(err, *p._errPos, []string{})
	} else {
		p.addErrAt(err, p.pt.position, []string{})
	}
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos *position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = *pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt *savepoint) {
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = *pt
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start *savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFromOffset(offset int) []byte {
	return p.data[offset:p.pt.position.offset]
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

// nolint: gocyclo
func (p *parser) parse(grammar *grammar) (val any, err error) {
	if grammar == nil {
		grammar = g
	}
	if len(grammar.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	p.rulesArray = grammar.rules
	p.buildRulesTable(grammar)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	var val any
	var ok bool
	if rule.varExists && !p.checkSkipCode() {
		p.pushV()
		val, ok = p.parseExprWrap(rule.expr)
		p.popV()
	} else {
		val, ok = p.parseExprWrap(rule.expr)
	}
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

// nolint: gocyclo
func (p *parser) parseExprWrap(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	skipCode := p.checkSkipCode()
	memo := p.memo1
	if skipCode {
		memo = p.memo2
	}

	setMemoized := func(pos int, expr any, val resultTuple) {
		if memo[pos] == nil {
			memo[pos] = map[any]*resultTuple{}
		}
		memo[pos][expr] = &val
	}

	getMemoized := func(expr any) *resultTuple {
		pos := p.pt.offset
		if memo[pos] == nil {
			return nil
		}
		return memo[pos][expr]
	}

	if m := getMemoized(expr); m != nil {
		p.restore(&m.end)
		return m.v, m.b
	}

	pos := p.pt.offset

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *andLogicalExpr:
		val, ok = p.parseAndLogicalExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *codeExpr:
		val, ok = p.parseCodeExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *notLogicalExpr:
		val, ok = p.parseNotLogicalExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *ruleIRefExpr:
		val, ok = p.parseRuleIRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}

	setMemoized(pos, expr, resultTuple{val, ok, p.pt})
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.checkSkipCode() {
		_, ok := p.parseExprWrap(act.expr)
		return nil, ok
	}

	p.spStack.push(&p.pt)
	val, ok := p.parseExprWrap(act.expr)
	start := p.spStack.pop()

	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		p._errPos = &start.position
		actVal := act.run(p)
		p._errPos = nil
		val = actVal
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	ok := and.run(p)
	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	return p.parseAndExprBase(and, false)
}

func (p *parser) parseAndLogicalExpr(and *andLogicalExpr) (any, bool) {
	return p.parseAndExprBase((*andExpr)(and), true)
}

func (p *parser) parseAndExprBase(and *andExpr, logical bool) (any, bool) {
	pt := p.pt

	p.scStack = append(p.scStack, true)
	_, ok := p.parseExprWrap(and.expr)
	p.scStack = p.scStack[:len(p.scStack)-1]

	matchedOffset := p.pt.offset
	p.restore(&pt)

	if logical {
		return nil, ok && p.pt.offset != matchedOffset
	}
	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, &p.pt.position, ".")
		return nil, false
	}
	p.failAt(true, &p.pt.position, ".")
	p.read()
	return nil, true
}

// nolint: gocyclo
func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	cur := p.pt.rn

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, &p.pt.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, &p.pt.position, chr.val)
				return nil, false
			}
			p.failAt(true, &p.pt.position, chr.val)
			p.read()
			return nil, true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, &p.pt.position, chr.val)
				return nil, false
			}
			p.failAt(true, &p.pt.position, chr.val)
			p.read()
			return nil, true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, &p.pt.position, chr.val)
				return nil, false
			}
			p.failAt(true, &p.pt.position, chr.val)
			p.read()
			return nil, true
		}
	}

	if chr.inverted {
		p.failAt(true, &p.pt.position, chr.val)
		p.read()
		return nil, true
	}
	p.failAt(false, &p.pt.position, chr.val)
	return nil, false
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		val, ok := p.parseExprWrap(alt)
		if ok {
			return val, ok
		}
	}
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	startOffset := p.pt.position.offset
	var val any
	var ok bool
	val, ok = p.parseExprWrap(lab.expr)
	if ok && lab.label != "" && !p.checkSkipCode() {
		m := p.vstack[len(p.vstack)-1]
		if lab.textCapture {
			m[lab.label] = string(p.sliceFromOffset(startOffset))
		} else {
			m[lab.label] = val
		}
	}
	return val, ok
}

func (p *parser) parseCodeExpr(code *codeExpr) (any, bool) {
	if !code.notSkip && p.checkSkipCode() {
		return nil, true
	}
	return code.run(p), true
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, &start.position, lit.want)
			p.restore(&start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, &start.position, lit.want)
	return nil, true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	ok := not.run(p)
	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	return p.parseNotExprBase(not, false)
}

func (p *parser) parseNotLogicalExpr(not *notLogicalExpr) (any, bool) {
	return p.parseNotExprBase((*notExpr)(not), true)
}

func (p *parser) parseNotExprBase(not *notExpr, logical bool) (any, bool) {
	pt := p.pt
	p.maxFailInvertExpected = !p.maxFailInvertExpected

	p.scStack = append(p.scStack, true)
	_, ok := p.parseExprWrap(not.expr)
	p.scStack = p.scStack[:len(p.scStack)-1]

	p.maxFailInvertExpected = !p.maxFailInvertExpected
	matchedOffset := p.pt.offset
	p.restore(&pt)

	if logical {
		return nil, !ok && p.pt.offset != matchedOffset
	}
	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	var vals []any
	var matched bool
	for {
		val, ok := p.parseExprWrap(expr.expr)
		if !ok {
			if len(vals) > 0 {
				return vals, matched
			}
			return nil, matched
		}
		matched = true
		if val != nil {
			vals = append(vals, val)
		}
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseRuleIRefExpr(ref *ruleIRefExpr) (any, bool) {
	return p.parseRuleWrap(p.rulesArray[ref.index])
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	var vals []any
	notSkipCode := p.checkSkipCode()

	pt := p.pt
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restore(&pt)
			return nil, false
		}
		if notSkipCode && val != nil {
			vals = append(vals, val)
		}
	}
	if len(vals) > 0 {
		return vals, true
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}
	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	var vals []any
	for {
		val, ok := p.parseExprWrap(expr.expr)
		if !ok {
			if len(vals) > 0 {
				return vals, true
			}
			return nil, true
		}
		if val != nil {
			vals = append(vals, val)
		}
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	val, _ := p.parseExprWrap(expr.expr)
	// whether it matched or not, consider it a match
	return val, true
}
