{
package issue18

import "fmt"

type ParserCustomData struct {}

func Parse(filename string, input []byte) (any, error) {
	p := newParser("", input)
	return p.parse(nil)
}

func main() {
    fmt.Println("with FailureTracking:")
    _, err := Parse("", []byte(`123455`))
    fmt.Println(err)
    _, err = Parse("", []byte(`

    1

    2

    3

    `))
    fmt.Println(err)
    _, err = Parse("", []byte(`

    1

    2

    x
    `))
    fmt.Println(err)
}
}

Program <- _ (X _)* _  EOF

X <- [0-9]

_ "whitespace" <- ( [ \t\r\n] )*

EOF <- !.
